# Generated by Django 5.1.5 on 2026-08-04 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardEquivalenceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('strategy', models.CharField(choices=[('canonical_identity', 'Canonical identity (default)'), ('normalized_name', 'Normalized name'), ('ability_equivalent', 'Equivalent ability text'), ('official_identifier', 'Official identifier'), ('admin_group', 'Admin-registered equivalence group')], default='admin_group', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('ability_text', models.TextField(blank=True)),
                ('flavor_text', models.TextField(blank=True)),
                ('grade', models.PositiveSmallIntegerField(choices=[(0, 'Grade 0'), (1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4')], db_index=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('shield', models.IntegerField(blank=True, null=True)),
                ('critical', models.PositiveSmallIntegerField(default=1)),
                ('card_type', models.CharField(choices=[('normal_unit', 'Normal Unit'), ('trigger_unit', 'Trigger Unit'), ('g_unit', 'G Unit'), ('order', 'Order'), ('set_order', 'Set Order'), ('blitz_order', 'Blitz Order'), ('token', 'Token')], db_index=True, max_length=24)),
                ('trigger', models.CharField(blank=True, choices=[('', '—'), ('critical', 'Critical'), ('draw', 'Draw'), ('front', 'Front'), ('heal', 'Heal'), ('stand', 'Stand'), ('over', 'Over')], default='', max_length=16)),
                ('nation', models.CharField(blank=True, choices=[('', '—'), ('dragon_empire', 'Dragon Empire'), ('dark_states', 'Dark States'), ('brandt_gate', 'Brandt Gate'), ('keter_sanctuary', 'Keter Sanctuary'), ('stoicheia', 'Stoicheia'), ('lyrical_monasterio', 'Lyrical Monasterio')], db_index=True, default='', max_length=32)),
                ('clan', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('race', models.CharField(blank=True, default='', max_length=64)),
                ('is_persona_ride', models.BooleanField(default=False)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('rules_data', models.JSONField(blank=True, default=dict)),
                ('equivalence_strategy', models.CharField(choices=[('canonical_identity', 'Canonical identity (default)'), ('normalized_name', 'Normalized name'), ('ability_equivalent', 'Equivalent ability text'), ('official_identifier', 'Official identifier'), ('admin_group', 'Admin-registered equivalence group')], default='canonical_identity', max_length=32)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['grade', 'card_type'], name='cards_card_grade_300951_idx'), models.Index(fields=['nation', 'grade'], name='cards_card_nation_6c1c61_idx'), models.Index(fields=['trigger'], name='cards_card_trigger_4fdd85_idx')],
            },
        ),
        migrations.CreateModel(
            name='CardPrinting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(db_index=True, max_length=64)),
                ('rarity', models.CharField(blank=True, max_length=32)),
                ('language', models.CharField(db_index=True, default='en', max_length=8)),
                ('illustrator', models.CharField(blank=True, max_length=200)),
                ('finish', models.CharField(blank=True, help_text='Treatment/finish, e.g. foil', max_length=64)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier_product_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('data_source', models.CharField(blank=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printings', to='cards.card')),
            ],
            options={
                'ordering': ('card_number',),
            },
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=500)),
                ('kind', models.CharField(default='full', help_text='full | thumbnail | art', max_length=24)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cards.cardprinting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('card_count', models.PositiveIntegerField(default=0)),
                ('external_source', models.CharField(blank=True, max_length=64)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ('-release_date', 'name'),
                'indexes': [models.Index(fields=['external_source', 'external_id'], name='cards_cards_externa_e878f9_idx')],
            },
        ),
        migrations.AddField(
            model_name='cardprinting',
            name='card_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printings', to='cards.cardset'),
        ),
        migrations.CreateModel(
            name='CardEquivalenceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalence_memberships', to='cards.card')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cards.cardequivalencegroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'card'), name='uniq_equivalence_member')],
            },
        ),
        migrations.CreateModel(
            name='CardExternalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(db_index=True, max_length=64)),
                ('identifier', models.CharField(db_index=True, max_length=128)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='cards.card')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'identifier'), name='uniq_external_identifier')],
            },
        ),
        migrations.CreateModel(
            name='CardFormatLegality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format_code', models.CharField(db_index=True, max_length=32)),
                ('legality', models.CharField(choices=[('legal', 'Legal'), ('not_legal', 'Not legal'), ('restricted', 'Restricted')], default='legal', max_length=16)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format_legalities', to='cards.card')),
            ],
            options={
                'verbose_name_plural': 'card format legalities',
                'constraints': [models.UniqueConstraint(fields=('card', 'format_code'), name='uniq_card_format')],
            },
        ),
        migrations.CreateModel(
            name='CardPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='cards.cardprinting')),
            ],
            options={
                'ordering': ('-recorded_at',),
                'indexes': [models.Index(fields=['printing', 'recorded_at'], name='cards_cardp_printin_f03bcf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cardprinting',
            index=models.Index(fields=['card', 'language'], name='cards_cardp_card_id_975a28_idx'),
        ),
        migrations.AddIndex(
            model_name='cardprinting',
            index=models.Index(fields=['data_source', 'supplier_product_id'], name='cards_cardp_data_so_43aa51_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardprinting',
            constraint=models.UniqueConstraint(fields=('card_number', 'card_set', 'language', 'finish'), name='uniq_printing_number_set_lang_finish'),
        ),
    ]
