# Generated by Django 5.1.5 on 2026-08-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_trigram_search'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='card',
            name='card_name_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='card_ability_trgm_idx',
        ),
        migrations.AlterField(
            model_name='cardset',
            name='code',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='cardset',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_source', 'external_id'), name='uniq_set_source_external_id'),
        ),
    ]
