# Generated by Django 5.1.5 on 2026-08-04 17:06

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_card_card_name_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='card_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(fields=['ability_text'], name='card_ability_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
