# Generated by Django 5.1.5 on 2026-08-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_card_name_trgm_idx_card_card_ability_trgm_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='nation',
            field=models.CharField(blank=True, choices=[('', '—'), ('dragon_empire', 'Dragon Empire'), ('dark_states', 'Dark States'), ('brandt_gate', 'Brandt Gate'), ('keter_sanctuary', 'Keter Sanctuary'), ('stoicheia', 'Stoicheia'), ('lyrical_monasterio', 'Lyrical Monasterio'), ('united_sanctuary', 'United Sanctuary'), ('dark_zone', 'Dark Zone'), ('magallanica', 'Magallanica'), ('zoo', 'Zoo'), ('star_gate', 'Star Gate')], db_index=True, default='', max_length=32),
        ),
    ]
