# Generated by Django 5.1.5 on 2026-08-04 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('power_level_change', 'Power level change'), ('banlist_official_change', 'Official banlist change'), ('format_rule_change', 'Format rule change'), ('match_result_correction', 'Match result correction'), ('disqualification', 'Disqualification'), ('bracket_change', 'Bracket change'), ('deck_submission_change', 'Deck submission change'), ('admin_action', 'Administrative action'), ('data_sync', 'Data synchronization')], db_index=True, max_length=48)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, default='api', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', 'created_at'], name='common_audi_action_f07e2b_idx'), models.Index(fields=['target_type', 'target_id'], name='common_audi_target__65ba7e_idx')],
            },
        ),
    ]
