# Generated by Django 5.1.5 on 2026-08-04 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0005_alter_card_nation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ('-valid_from',),
            },
        ),
        migrations.CreateModel(
            name='GameFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_official', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FormatConstructionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copies_per_identity', models.PositiveIntegerField(default=4)),
                ('nation_locked', models.BooleanField(default=True, help_text='Single Nation per deck')),
                ('clan_locked', models.BooleanField(default=False)),
                ('requires_first_vanguard', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('rule_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='construction_rule', to='formats.formatruleversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormatTriggerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_triggers', models.PositiveIntegerField(default=16)),
                ('per_type_limits', models.JSONField(blank=True, default=dict)),
                ('over_trigger_limit', models.PositiveIntegerField(default=1)),
                ('counted_zones', models.JSONField(blank=True, default=list)),
                ('rule_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_rule', to='formats.formatruleversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formatruleversion',
            name='game_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_versions', to='formats.gameformat'),
        ),
        migrations.CreateModel(
            name='FormatException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cards.card')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='formats.formatruleversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rule_version', 'card'), name='uniq_format_exception')],
            },
        ),
        migrations.CreateModel(
            name='FormatZoneRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.CharField(max_length=12)),
                ('min_count', models.PositiveIntegerField(default=0)),
                ('max_count', models.PositiveIntegerField(default=0)),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_rules', to='formats.formatruleversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rule_version', 'zone'), name='uniq_zone_rule')],
            },
        ),
        migrations.AddConstraint(
            model_name='formatruleversion',
            constraint=models.UniqueConstraint(fields=('game_format', 'version'), name='uniq_format_version'),
        ),
    ]
