# Generated by Django 5.1.5 on 2026-08-04 17:38

import secrets

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"


def backfill_referral_codes(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    used = set(
        UserProfile.objects.exclude(referral_code="").exclude(referral_code=None)
        .values_list("referral_code", flat=True)
    )
    for profile in UserProfile.objects.filter(models.Q(referral_code="") | models.Q(referral_code=None)):
        while True:
            code = "".join(secrets.choice(_ALPHABET) for _ in range(8))
            if code not in used:
                used.add(code)
                break
        profile.referral_code = code
        profile.save(update_fields=["referral_code"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cards', '0005_alter_card_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_referral_codes, noop),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FavoriteCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_fa_user_id_7f792b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'card'), name='uniq_favorite_card')],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], db_index=True, default='pending', max_length=12)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['addressee', 'status'], name='accounts_fr_address_a49795_idx')],
                'constraints': [models.UniqueConstraint(fields=('requester', 'addressee'), name='uniq_friendship_pair'), models.CheckConstraint(condition=models.Q(('requester', models.F('addressee')), _negated=True), name='no_self_friendship')],
            },
        ),
    ]
