# Generated by Django 5.1.5 on 2026-08-04 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='bracket',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='is_draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='loser_advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='loser_next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser_feeder_matches', to='tournaments.tournamentmatch'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='loser_next_slot',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
