# Generated by Django 5.1.5 on 2026-08-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentmatch_bracket_tournamentmatch_is_draw_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='power_policy',
        ),
    ]
