# Generated by Django 5.1.5 on 2026-08-06 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deck_power_stars'),
        ('tournaments', '0003_remove_tournament_power_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ace_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ace_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ace_reveal',
            field=models.CharField(choices=[('public', 'Public'), ('hidden_until_first_use', 'Hidden until first use')], default='public', max_length=24),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ace_rule',
            field=models.CharField(choices=[('manual_once', 'Player uses Ace once'), ('replace_draw', 'Ace replaces a draw once'), ('weighted_random', 'Ace weighted in random'), ('extra_in_rotation', 'Ace appears extra in rotation'), ('tiebreak_wins', 'Ace wins as tiebreak'), ('visual_only', 'Visual only')], default='visual_only', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='allow_draws',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='checkin_opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='deck_selection_mode',
            field=models.CharField(choices=[('manual', 'Manual secret pick'), ('random_free', 'Random — free repeats'), ('random_no_consecutive', 'Random — no consecutive repeat'), ('random_rotation', 'Random — rotation (all before repeat)'), ('predetermined_order', 'Predetermined random order'), ('choose_from_random', 'Choose from N random')], default='random_rotation', max_length=24),
        ),
        migrations.AddField(
            model_name='tournament',
            name='decks_per_player',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='tournament',
            name='draw_timing',
            field=models.CharField(choices=[('before_pairing', 'Before pairing'), ('after_pairing', 'After pairing'), ('auto_round_start', 'Auto at round start'), ('manual_owner', 'Manual by owner')], default='auto_round_start', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format_kind',
            field=models.CharField(choices=[('points', 'Points only'), ('bracket', 'Bracket only'), ('hybrid', 'Hybrid (points → bracket)')], default='points', max_length=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='hybrid_advance_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='kind',
            field=models.CharField(choices=[('standard', 'Standard (single deck)'), ('roster', 'Roster championship')], db_index=True, default='standard', max_length=12),
        ),
        migrations.AddField(
            model_name='tournament',
            name='league_double_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_deck_power',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_deck_power',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_bye',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_draw',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_loss',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_win',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tournament',
            name='power_cap',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='tournament',
            name='random_options_count',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='reveal_lists_after_end',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='roster_visibility',
            field=models.CharField(choices=[('open', 'Open'), ('partial', 'Partially open'), ('closed', 'Closed')], default='partial', max_length=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='seed_source',
            field=models.CharField(choices=[('random', 'Random'), ('manual', 'Manual'), ('platform_ranking', 'Platform ranking')], default='random', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sequence_opponent_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('hidden', 'Hidden from opponents')], default='hidden', max_length=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sequence_self_visibility',
            field=models.CharField(choices=[('from_start', 'Visible from start'), ('each_round', 'Revealed each round')], default='each_round', max_length=12),
        ),
        migrations.CreateModel(
            name='TournamentPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('warning', 'Warning'), ('game_loss', 'Game loss'), ('match_loss', 'Match loss'), ('points_deduction', 'Points deduction'), ('disqualification', 'Disqualification')], max_length=20)),
                ('points', models.SmallIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.tournamentmatch')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='tournaments.tournamentparticipant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TournamentRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('confirmed', 'Confirmed'), ('locked', 'Locked')], db_index=True, default='draft', max_length=12)),
                ('power_used', models.PositiveSmallIntegerField(default=0)),
                ('is_over_cap', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='tournaments.tournamentparticipant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='tournaments.tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RosterDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_ace', models.BooleanField(default=False)),
                ('banlist_valid', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, max_length=140)),
                ('slot', models.PositiveSmallIntegerField(default=0)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('locked', models.BooleanField(default=False)),
                ('power_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='decks.decksnapshot')),
                ('source_deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='decks.deck')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='tournaments.tournamentroster')),
            ],
            options={
                'ordering': ('slot', 'order_index'),
            },
        ),
        migrations.CreateModel(
            name='AceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('used', 'Used'), ('replaced_draw', 'Replaced a draw'), ('revealed', 'Revealed')], max_length=16)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.tournamentmatch')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ace_events', to='tournaments.tournamentroster')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MatchDeckSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('random', 'Random'), ('predetermined', 'Predetermined'), ('choose_from_random', 'Choose from random')], default='random', max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('revealed', models.BooleanField(default=False)),
                ('is_ace_used', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('eligible', models.JSONField(blank=True, default=list)),
                ('rule_used', models.CharField(blank=True, max_length=32)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_selections', to='tournaments.tournamentmatch')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_selections', to='tournaments.tournamentparticipant')),
                ('roster_deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='tournaments.rosterdeck')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'participant'), name='uniq_match_selection')],
            },
        ),
        migrations.CreateModel(
            name='DeckDrawLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(blank=True, default=list)),
                ('rule', models.CharField(blank=True, max_length=32)),
                ('admin_intervention', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_logs', to='tournaments.tournamentparticipant')),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draw_logs', to='tournaments.tournamentround')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_logs', to='tournaments.tournament')),
                ('result_deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.rosterdeck')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tournament', 'round'], name='tournaments_tournam_286e95_idx')],
            },
        ),
        migrations.CreateModel(
            name='RosterDeckSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveSmallIntegerField()),
                ('revealed', models.BooleanField(default=False)),
                ('roster_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournaments.rosterdeck')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='tournaments.tournamentroster')),
            ],
            options={
                'ordering': ('round_number',),
                'constraints': [models.UniqueConstraint(fields=('roster', 'round_number'), name='uniq_roster_sequence')],
            },
        ),
        migrations.AddConstraint(
            model_name='rosterdeck',
            constraint=models.UniqueConstraint(fields=('roster', 'source_deck'), name='uniq_roster_deck'),
        ),
    ]
