# Generated by Django 5.1.5 on 2026-08-06 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='power_stars',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Força do deck escolhida pelo dono (1–5).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
