# Generated by Django 5.1.5 on 2026-08-04 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0005_alter_card_nation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('objective', models.CharField(blank=True, max_length=255)),
                ('format_code', models.CharField(db_index=True, default='standard', max_length=32)),
                ('category', models.CharField(choices=[('official', 'Official'), ('community', 'Community'), ('tournament_custom', 'Tournament custom')], db_index=True, default='community', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('is_listed', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('forked_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='banlists.banlist')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='BanlistComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=2000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banlist_comments', to=settings.AUTH_USER_MODEL)),
                ('banlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='banlists.banlist')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BanlistVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=12)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('banlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='banlists.banlist')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='BanlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restriction_type', models.CharField(choices=[('banned', 'Banned'), ('limit_to_1', 'Limit to 1'), ('limit_to_2', 'Limit to 2'), ('limit_to_n', 'Limit to N'), ('first_vanguard_forbidden', 'First Vanguard forbidden'), ('choice_restriction', 'Choice restriction'), ('max_distinct_from_group', 'Max distinct from group'), ('max_total_from_group', 'Max total from group'), ('deck_dependent_restriction', 'Deck-dependent restriction'), ('allowed_exception', 'Allowed exception'), ('unrestricted_history', 'Unrestricted (history)')], max_length=32)),
                ('limit_value', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banlist_entries', to='cards.card')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='banlists.banlistversion')),
            ],
        ),
        migrations.AddField(
            model_name='banlist',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='banlists.banlistversion'),
        ),
        migrations.CreateModel(
            name='RestrictionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition_type', models.CharField(choices=[('nation', 'Nation'), ('clan', 'Clan'), ('format', 'Format'), ('has_card', 'Deck contains card'), ('rideline', 'Rideline')], max_length=16)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='banlists.banlistentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestrictionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('kind', models.CharField(choices=[('choice', 'Choice (pick one)'), ('max_distinct', 'Max distinct identities'), ('max_total', 'Max total copies')], default='choice', max_length=16)),
                ('limit_value', models.PositiveIntegerField(default=1, help_text='Max distinct/total; for CHOICE = 1')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restriction_groups', to='banlists.banlistversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='banlistentry',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='banlists.restrictiongroup'),
        ),
        migrations.CreateModel(
            name='RestrictionGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('per_card_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cards.card')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='banlists.restrictiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='BanlistFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='banlists.banlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banlist_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('banlist', 'user'), name='uniq_banlist_favorite')],
            },
        ),
        migrations.CreateModel(
            name='BanlistLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='banlists.banlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banlist_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('banlist', 'user'), name='uniq_banlist_like')],
            },
        ),
        migrations.AddConstraint(
            model_name='banlistversion',
            constraint=models.UniqueConstraint(fields=('banlist', 'version'), name='uniq_banlist_version'),
        ),
        migrations.AddIndex(
            model_name='banlist',
            index=models.Index(fields=['category', 'format_code'], name='banlists_ba_categor_aa212a_idx'),
        ),
        migrations.AddIndex(
            model_name='banlistentry',
            index=models.Index(fields=['version', 'restriction_type'], name='banlists_ba_version_d0da54_idx'),
        ),
        migrations.AddConstraint(
            model_name='restrictiongroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'card'), name='uniq_group_member'),
        ),
    ]
