# Generated by Django 5.1.5 on 2026-08-04 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0005_alter_card_nation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerLevelChangeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('label', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PowerLevelScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default 1-10', max_length=80)),
                ('min_value', models.PositiveSmallIntegerField(default=1)),
                ('max_value', models.PositiveSmallIntegerField(default=10)),
                ('descriptions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentPowerPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('none', 'No power restriction'), ('max_per_card', 'Max power level per card'), ('range', 'Allowed range'), ('max_above', 'Max cards above a level'), ('point_budget', 'Total power-point budget'), ('max_copies_above', 'Max copies of cards above a level'), ('custom', 'Custom combination')], default='none', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentPowerPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('none', 'No power restriction'), ('max_per_card', 'Max power level per card'), ('range', 'Allowed range'), ('max_above', 'Max cards above a level'), ('point_budget', 'Total power-point budget'), ('max_copies_above', 'Max copies of cards above a level'), ('custom', 'Custom combination')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='powerlevel.tournamentpowerpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardPowerLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_code', models.CharField(db_index=True, max_length=32)),
                ('previous_value', models.SmallIntegerField(blank=True, null=True)),
                ('new_value', models.SmallIntegerField(blank=True, null=True)),
                ('justification', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('admin_single', 'Admin — single edit'), ('admin_bulk', 'Admin — bulk edit'), ('import', 'Import'), ('ai_suggestion', 'AI suggestion (never auto-published)')], default='admin_single', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_history', to='cards.card')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['card', 'format_code', 'created_at'], name='powerlevel__card_id_ebdf1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CardPowerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format_code', models.CharField(db_index=True, max_length=32)),
                ('value', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=12)),
                ('justification', models.TextField(blank=True)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, help_text='1-5, optional', null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_levels', to='cards.card')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='powerlevel.powerlevelscale')),
            ],
            options={
                'indexes': [models.Index(fields=['format_code', 'status'], name='powerlevel__format__57173b_idx')],
                'constraints': [models.UniqueConstraint(fields=('card', 'format_code'), name='uniq_card_format_power')],
            },
        ),
    ]
