# Generated by Django 5.1.5 on 2026-08-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerlevel', '0001_initial'),
        ('tournaments', '0003_remove_tournament_power_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpowerlevel',
            name='card',
        ),
        migrations.RemoveField(
            model_name='cardpowerlevel',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='cardpowerlevel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='cardpowerlevelhistory',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='cardpowerlevelhistory',
            name='card',
        ),
        migrations.DeleteModel(
            name='PowerLevelChangeReason',
        ),
        migrations.RemoveField(
            model_name='tournamentpowerpolicy',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tournamentpowerpolicyrule',
            name='policy',
        ),
        migrations.DeleteModel(
            name='PowerLevelScale',
        ),
        migrations.DeleteModel(
            name='CardPowerLevel',
        ),
        migrations.DeleteModel(
            name='CardPowerLevelHistory',
        ),
        migrations.DeleteModel(
            name='TournamentPowerPolicy',
        ),
        migrations.DeleteModel(
            name='TournamentPowerPolicyRule',
        ),
    ]
