# Generated by Django 5.1.5 on 2026-08-04 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='e.g. tcgcsv', max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('base_url', models.URLField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('rate_limit_per_sec', models.PositiveIntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('sets', 'Sets'), ('products', 'Products / cards'), ('prices', 'Prices'), ('images', 'Images'), ('full', 'Full sync')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('is_incremental', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('log', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('triggered_by', models.CharField(blank=True, help_text="username or 'system'", max_length=64)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='imports.datasource')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RawImportPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='imports.importbatch')),
            ],
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['source', 'kind', 'status'], name='imports_imp_source__f3a894_idx'),
        ),
        migrations.AddIndex(
            model_name='rawimportpayload',
            index=models.Index(fields=['batch', 'external_id'], name='imports_raw_batch_i_7f91c1_idx'),
        ),
    ]
